language: scala
jdk:
   - oraclejdk8
   - openjdk8
   - oraclejdk11
   - openjdk11
scala:
   - 2.11.12
   - 2.12.8
   - 2.13.0
# These directories are cached to a cloud storage provider "close" to the infrastructure the builds run on.
cache:
   directories:
      - $HOME/.ivy2/cache
      - $HOME/.sbt
before_cache:
   # Cleanup the cached directories to avoid unnecessary cache updates
   - rm -fv $HOME/.ivy2/.sbt.ivy.lock
   - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
   - find $HOME/.sbt        -name "*.lock"               -print -delete
